{"name": "test_get_optional_username_http_exception", "status": "passed", "description": "\n        Covers: security(request) raises HTTPException => propagate.\n        ", "start": 1755785114021, "stop": 1755785114023, "uuid": "798866bc-ce50-46d6-80f4-fba426909480", "historyId": "7454695a72a4b3654efb7ecff6cc9e44", "testCaseId": "7454695a72a4b3654efb7ecff6cc9e44", "fullName": "tests.test_auth.TestAuthWithMocks#test_get_optional_username_http_exception", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthWithMocks"}, {"name": "host", "value": "LAPTOP-J12RM8I3"}, {"name": "thread", "value": "373292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py", "TestAuthWithMocks"]}